home:
  path: /
  controller: App\Controller\HomeController::index

properties:
  path: /biens
  controller: App\Controller\PropertyController::index

property.show:
  path: /biens/{slug}-{id}
  controller: App\Controller\PropertyController::show
  requirements:
    slug: '[a-z0-9\-]+'

admin.property.index:
  path: /admin
  controller: App\Controller\Admin\PropertyController::index

admin.property.edit:
  path: /admin/property/{id}
  controller: App\Controller\Admin\PropertyController:edit
  methods: GET|POST
  requirements:
    id: \d+

admin.property.new:
  path: /admin/property/new
  controller: App\Controller\Admin\PropertyController::new

admin.property.delete:
  path: /admin/property/{id}
  controller: App\Controller\Admin\PropertyController::delete
  methods: DELETE
  requirements:
    id: \d+

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout

controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation
